### ISSUE TITLE
Make sure everyone can compile

### ISSUE THREAD

**Issue by ekfriis** [uwcms/cms-calo-layer1#1]
@tsarangi @dabelknap @nwoods

Please make sure you can compile the as described in the README

**Comment by ekfriis** [comment]
Hi all, can I close this?  Have you compiled everything successfully?

**Comment by nwoods** [comment]
It worked for me.

**Comment by dabelknap** [comment]
What machine do I need to be on for this to work?

**Comment by tsarangi** [comment]
I could compile it yesterday. Haven't tried today if anything has changed... @dabelknap, I compiled it on ayinger.hep.wisc.edu

**Comment by dabelknap** [comment]
Works for me.

**Comment by ekfriis** [comment]
woo, the first task is done!
