### ISSUE TITLE
oRSC Back-End Doesn't Reach "main()"

### ISSUE THREAD

**Issue by dabelknap** [uwcms/cms-calo-layer1#18]
This problem was discovered in an attempt to run `orsc_be_vmestream_echo_test` on the oRSC BE (Issue #8).

The software was loaded onto the oRSC BE using the following steps (assuming everything is compiled):

``` shell
$ cd cms-calo-layer1/orsc_be_vmestream_echo_test
$ xmd
XMD$ connect mb mdm
XMD$ dow payload.elf
XMD$ read_uart
XMD$ run
```

There is a `xil_printf` statement just after the start of `main()` (https://github.com/uwcms/cms-calo-layer1/blob/master/orsc_be_vmestream_echo_test/src/vmestream_echo.c#L27), and it is never reached.

Stepping through the Assembly (`payload.S`) with the debugger, I found what appears to be the problem. Before `main` is called, it enters a function called `__init`, which in turn calls `frame_dummy`. When end of `frame_dummy` is reached, instead of returning to `__init`, it jumps to an address outside of the address range of the program. 

```
XMD% stp
     19C:   B60F0008  rtsd     r15, 8
     1A0:   3021001C  addik    r1 , r1 , 28   # end of <frame_dummy>

XMD% stp
    FEF4:   00000000  add      r0 , r0 , r0   # jumps outside the address range of the program

XMD% stp
    FEF8:   00000000  add      r0 , r0 , r0 
...
```

When nothing is found at the address `0xfef4`, it move to the next address. It finds nothing here so it continues in this way to address `0xfffc`.

```
...
XMD% stp
    FFFC:   00000000  add      r0 , r0 , r0

XMD% stp
   10000:   B0000000  imm      0
   10004:   B8080050  brai     80

XMD% stp
      50:   B0001000  imm      4096            # back to the beginning
      54:   31A009A0  addik    r13, r0 , 2464
```

At this point, the program returns to the beginning, and we are stuck in an infinite loop.

**Comment by ekfriis** [comment]
My first guess is that this is symptomatic of the compiler linker script "ldscript.ld" being confused about the correct locations of where it is okay to store the program in the device memory. In #19 I regenerated the linker script which seems to have changed things, perhaps it will fix this problem.

**Comment by dabelknap** [comment]
PR #19 fixed this: the program can now enter `main()`
