### ISSUE TITLE
/opt/AMC13/ecad_activate_amc13.sh needs python 2.6 at 904

### ISSUE THREAD

**Issue by ekfriis** [uwcms/cms-calo-layer1#21]
I think it got killed by a Quattor update.  I can't find it with yum in SLC - I'll keep looking, but any tips are appreciated @jtikalsky

**Comment by ekfriis** [comment]
For the record, here is the error I get:

```
$ /opt/AMC13/ecad_activate_amc13.sh 16
/usr/bin/env: python2.6: No such file or directory
```

**Comment by ekfriis** [comment]
@pklabbers has fixed this.  It gives the expected (slightly strange) output now:

```
[friis@vmepc-e1x07-13-01 cms-calo-layer1]$ /opt/AMC13/ecad_activate_amc13.sh 16
Using IP address 223 for Virtex
Using IP address 222 for Spartan
Serial: 16
Status: 11 - Unknown Status
Status 9 Expected
Unexpected status recieved!
```

Running `cat /var/log/clock_init.log` on the CTP6 shows that the clocks are now configured correctly:

```
~ # cat /var/log/clock_init.log
SETTING REGISTER MAP
REGISTER MAP IS SET
Waiting for Input Clock...
Detected.
Waiting for PLL Lock...
Acquired.
Configuration Complete.
```

Thanks Pam!!

**Comment by jtikalsky** [comment]
This output is fine.  When I wrote this script, I didn't have any data 
on what the status register codes that were valid are.  If 11 is good, 
feel free to add it to the python script as 'expected', but the warning 
at the end of that script has no strong meaning, given this.
