### ISSUE TITLE
Document how to recover from Xilinx "JTAG Cable not Found" error

### ISSUE THREAD

**Issue by ekfriis** [uwcms/cms-calo-layer1#23]
Hi @jtikalsky, can you put on the wiki [1] instructions on how to recover from the JTAG cable driver getting wedged on ayinger/spaten so Nate/Tapas can fix it when you aren't around?

Do you know what causes the problem?

cc @nwoods @tsarangi 

[1] https://github.com/uwcms/cms-calo-layer1/wiki

**Comment by ekfriis** [comment]
I am now stuck on the same problem at 904.  I've reran:

``` shell
cd /opt/Xilinx/14.4/ISE_DS/common/bin/lin/install_script/install_drivers
sudo ./install_drivers
```

which tells me

```
--File /sbin/fxload does not exist.

--The fxload package is not installed. This package is required to ensure correct Platform Cable USB
--operation and must be installed by the user or System Administrator. This warning can be safely ignored
--if you are using the Parallel Cable III or Parallel Cable IV.
```

So now I am looking for an SLC fxload to install.  Maybe these links [1,2] will help.

[1] https://www.wrbishop.com/fpga/how-to-configure-xilinx-fpga-design-suite-13-3-under-rhelcentos-6-x-fedora-15/
[2] http://scientificlinuxforum.org/index.php?showtopic=2185

**Comment by ekfriis** [comment]
I installed `fxload` by downloading the RPM from here [1].  The final instructions that made it work again are:

```
# on cms904usr, since l1ts-rct-01 can't see the net
wget http://dl.atrpms.net/el5-x86_64/atrpms/stable/fxload-2008_10_13-2.el5.x86_64.rpm
# l1ts-rct-01
sudo yum  --nogpgcheck install fxload-2008_10_13-2.el5.x86_64.rpm
cd /opt/Xilinx/14.4/ISE_DS/common/bin/lin/install_script/install_drivers
sudo ./install_drivers
sudo chmod 666 /dev/windrvr6
```

@jtikalsky can you confirm this is a sane procedure? if so I will put it on the twiki.  @pklabbers - can these steps get added to quattor?

[1] http://pkgs.org/centos-5-rhel-5/atrpms-x86_64/fxload-2008_10_13-2.el5.x86_64.rpm.html

**Comment by ekfriis** [comment]
Our cable stopped working after I unplugged it. This was due to Quattor erasing /sbin/fxload (how rude).  Could something similar be happening at Chamberlin via puppet? We are working to get it into the Quattor profile here.

**Comment by ekfriis** [comment]
I think the instructions above are sufficient, I added it to the wiki. https://github.com/uwcms/cms-calo-layer1/wiki/Xilinx-SDK-XMD-and-JTAG

**Comment by jtikalsky** [comment]
This is sane.
