### ISSUE TITLE
Make sure we can compile everything at 904

### ISSUE THREAD

**Issue by ekfriis** [uwcms/cms-calo-layer1#3]
We may need to install Petalinux, Xilinx, etc.

**Comment by ekfriis** [comment]
@dabelknap, can you try compiling things on l1ts-rct-01?  You need to bounce through cms904usr to get there. Probably you need to checkout from github while on cms904usr, l1ts-rct-01 is not connected to the net.

**Comment by dabelknap** [comment]
`softipbus` and `cms-calo-level1` compile. Is that all we need for this issue?

**Comment by ekfriis** [comment]
Yes :)
