### ISSUE TITLE
Can't make blinky lights on oRSC

### ISSUE THREAD

**Issue by ekfriis** [uwcms/cms-calo-layer1#35]
With the current FE oRSC bitfile, we can't make the LEDs light up via direct XMD writes.  See the Makefile [1] for the xmd commands, or the instructions below.

Once should be able to (on a machine connected to oRSC via XMD):

```
# power cycle oRSC - lights will be blinky from Tom's BE bitfile
cd cms-calo-layer1/rct2orsc_byhand
# upload latest FE bitfile - lights are off
make orscfebits 
# write LED control registers via XMD
make lightson
# turn off LEDs
make lightsoff
```

Expected behavior: lights go on and off
Actual behavior: lights stay off

[1] https://github.com/uwcms/cms-calo-layer1/blob/master/rct2orsc_byhand/Makefile#L42

**Comment by ekfriis** [comment]
Private email from Mathias:

> The problem is that for some reason you got confused which FPGA the LEDs are connected to.  This may have been my fault :-)  They are connected to the BACKEND FPGA.  And the following are the addresses:
> 
> ```
>         when x"10008000" => fpled1grnena_b_reg  <= BRAM_WRDATA_A(0)   ;
>         when x"10008004" => fpled1redena_b_reg  <= BRAM_WRDATA_A(0)   ;
>         when x"10008008" => fpled2grnena_b_reg  <= BRAM_WRDATA_A(0)   ;
>         when x"1000800C" => fpled2redena_b_reg  <= BRAM_WRDATA_A(0)   ;
>         when x"10008010" => fpled3grnena_b_reg  <= BRAM_WRDATA_A(0)   ;
>         when x"10008014" => fpled3redena_b_reg  <= BRAM_WRDATA_A(0)   ;
> ```

**Comment by dabelknap** [comment]
`make orscbebits` needs to be run before the LEDs can be controlled.

**Comment by ekfriis** [comment]
Hooray, the lights blink!  Thanks Austin
