### ISSUE TITLE
Update oRSC HW XMLs and BSPs

### ISSUE THREAD

**Issue by ekfriis** [uwcms/cms-calo-layer1#5]
We need to update the oRSC XMLs and BSPs to whatever the latest development is from Mathias.

**Comment by ekfriis** [comment]
@tsarangi do you know when Mathias is coming back?  do you think you could gently ask him if he already has these handy?

**Comment by tsarangi** [comment]
Don't know when he is coming back. I had sent an email to him about other thing and still waiting for a response. May be you should give a try this time ;-)

**Comment by ekfriis** [comment]
I started documenting how to do this using the GUI at https://github.com/uwcms/cms-calo-layer1/wiki/UsingXilinxGUI

Still need an actual updated HW XML from Mathias.

**Comment by ekfriis** [comment]
Mathias reports the Microblaze part of the bitfile has not changed, so the HW XML does not change and this task is not necessary.
