### ISSUE TITLE
Put VMEStream in cms-calo-layer1 package

### ISSUE THREAD

**Issue by ekfriis** [uwcms/cms-calo-layer1#7]
I don't think there is a need for it to be in a separate repo, since it will never be used outside the context of the oRSC.  We can move it to a subdirectory in cms-calo-layer1, like spistream [1]

[1] https://github.com/uwcms/cms-calo-layer1/tree/master/spistream

**Comment by ekfriis** [comment]
Hi @dabelknap not Nate, 

I meant to ask you to do this - I think it is easiest to just put VMEStream as a subdirectory into this package, since things in here will depend on it, but nothing else will.

Evan

**Comment by ekfriis** [comment]
(I would just merge caen into master and then transfer it over here).

**Comment by dabelknap** [comment]
How do you want to do this? Should I add it as a submodule, or merge it with `git subtree`?

**Comment by ekfriis** [comment]
Subtree
