### ISSUE TITLE
Write oRSC BE VMEStream -> SPIStream code

### ISSUE THREAD

**Issue by ekfriis** [uwcms/cms-calo-layer1#9]
This standalone package should live on the oRSC backend, receive data over VMEstream and forward it via SPIStream to the backend.

Will be 1/2 based on the validation code in #8, and half on orsc_be_spi_echo_test.

**Comment by ekfriis** [comment]
Hi @dabelknap, can you try to do this?  It should live in `orsc_be_ipbus` and the first version should be similar to #8 and orsc_be_spi_echo_test, except instead of echoing like #8 you connect the VMEstream receive cbuffer to the SPIStream transmit cbuffer, and vice versa.

**Comment by dabelknap** [comment]
In other words, I use `orsc_fe_spi_echo_test/src/spiecho.c` and `orsc_be_vmestream_echo_test/src/vmestream_echo.c` as starting points, and place the result in `orsc_be_ipbus`. Call it `vme2spi.c`, or something simliar. Sound right?

**Comment by ekfriis** [comment]
Exactly!

**Comment by dabelknap** [comment]
How exactly is a SPI transfer triggered? I don't see any "transfer" calls made in the loop: https://github.com/uwcms/cms-calo-layer1/blob/master/orsc_be_spi_echo_test/src/spiecho.c#L122

**Comment by dabelknap** [comment]
Okay, so data is transferred automatically in/out of the SPIStream buffers without explicit calls (https://github.com/dabelknap/cms-calo-layer1/tree/master/spistream/README.md), correct?

**Comment by ekfriis** [comment]
Yes, it is "interrupt driven" - however, there may be an error in how it is
setup, since it is untested.

Checkout uart_echo_test for a working example of interrupt handling (for a
different device type).

**Comment by ekfriis** [comment]
Done, to be tested.
